# Generated by Django 5.2 on 2025-04-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_userprofile_id_alter_userprofile_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='checked_in',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='checked_in_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='checked_out_at',
        ),
        migrations.AlterField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
