# Generated by Django 5.2 on 2025-04-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_booking_checked_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_occupancy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
