# Generated by Django 5.2 on 2025-04-14 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_room_current_occupancy_alter_room_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='current_occupancy',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
    ]
