# Generated by Django 5.2 on 2025-04-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_room_current_occupancy_remove_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=17000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
