# Generated by Django 5.2 on 2025-04-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_booking_checked_in_booking_checked_in_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='room',
            name='current_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
