# Generated by Django 5.2 on 2025-04-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_room_capacity_remove_room_current_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=3),
        ),
    ]
